export const REQUEST='REQUEST'
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const FAILURE="FAILURE"
export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const PATCH_SUCCESS="PATCH_SUCCESS"